export const VISITOR = 'visitor'
export const CUSTOMER = 'customer'
export const BUSINESS_PROSPECT = 'business:prospect'
export const BUSINESS_CUSTOMER = 'business:customer'
export const RESIDENTIAL_PROSPECT = 'resi:prospect'
export const RESIDENTIAL_CUSTOMER = 'resi:customer'
export const ENTERPRISE_USER = 'enterprise user'
