export const FRGUIDE = 'frguide'
export const FRGUIDE_BOLD = 'frguide bold'
export const FRGUIDE_BLACK = 'frguide black'
export const FRGUIDE_HEAVY = 'frguide heavy'
export const PP_OBJECT_SANS = 'PP Object Sans'
export const PP_OBJECT_SANS_MEDIUM = 'PP Object Sans Medium'
export const PP_OBJECT_SANS_BOLD = 'PP Object Sans Bold'
