// As new colors are introduced, we can add them in the format below:

const colors = {
  white: '#ffffff',
  opaqueWhite: 'rgba(255, 255, 255, 0.6)',
  highlightWhite: 'rgba(255, 255, 255, 0.1)',
  gray10: '#FAFAFA',
  gray20: '#F4F4F4',
  gray30: '#E0E0E0',
  gray40: '#CCCCCC',
  gray50: '#333',
  gray60: '#58595b',
  gray70: '#57595c',
  gray80: '#fefefe',
  gray90: '#e5e5e5',
  aqua: '#c7ebf2',
  mineShaft: '#222',
  activeGray: '#278189',
  activeDarkGray: '#206c72',
  maskedGray: '#d1d2d4',
  yellow: '#FDB831',
  red: '#D9272C',
  darkBlue: '#17355e',
  lightBlue: '#2B7E93',
  darkRed: '#df4841',
  secondaryRed: '#df4841',
  lightRed: '#d9272d',
  brightRed: '#ff0037',
  offBlack: '#171718',
  black: '#161617',
  nightRider: '#353535',
  grayBorder: '#777',
  boxShadow: '#32323230',
  shadowBlack: '#00000024',
  opaqueRed: '#d9272ceb',
  backgroundGray: '#57585b',
  slateBlue: '#e3f5f8',
  black10: '#0a0f11',
  black20: '#090d1b',
  greenishGrey: '#16282e',
  green: '#5dbd58',
  midnightExpress: '#141928',
  shuttleGray: '#5b5e69',
  blackRock: '#2c303e',
  torchRed: '#ff0005',
  blackCoral: '#5b5e69',
  greenishBlue: '#96fff5',
  grayOpacity50: '#898C93',

  // NEW DESIGN COLORS
  dark: '#141928',
  secondary: '#96fff5',
  backgroundDarkBlue: '#090F2B',
  grey: '#f3f4f4',
  borderGrey: '#C4C5C9',
  newBackgroundGray: '#F3F4F4',
  crimsonRed: '#D9312A',
  lightBorderGrey: '#f2f4f4',
  secondaryLight: '#EAFFFD',
}

export default {
  main: {
    white: colors.white,
    lightGray: colors.gray20,
    activeGray: colors.activeGray,
    borderLightGray: colors.gray30,
    gray: colors.gray40,
    gray50: colors.gray50,
    gray90: colors.gray90,
    primaryRed: colors.red,
    darkRed: colors.darkRed,
    secondaryRed: colors.secondaryRed,
    lightRed: colors.lightRed,
    darkBlue: colors.darkBlue,
    accentYellow: colors.yellow,
    backgroundGray: colors.gray10,
    darkGray: colors.gray70,
    offBlack: colors.offBlack,
    textGray: colors.gray60,
    maskedGray: colors.maskedGray,
    black: colors.black,
    lightBlue: colors.lightBlue,
    nightRider: colors.nightRider,
    grayBorder: colors.grayBorder,
    boxShadow: colors.boxShadow,
    shadowBlack: colors.shadowBlack,
    opaqueRed: colors.opaqueRed,
    activeDarkGray: colors.activeDarkGray,
    aqua: colors.aqua,
    bgGray: colors.gray80,
    headingBackgroundGray: colors.backgroundGray,
    slateBlue: colors.slateBlue,
    blackBackground: colors.black10,
    nightDarkBlack: colors.black20,
    greenishGrey: colors.greenishGrey,
    green: colors.green,
    midnightExpress: colors.midnightExpress,
    opaqueWhite: colors.opaqueWhite,
    highlightWhite: colors.highlightWhite,
    brightRed: colors.brightRed,
    shuttleGray: colors.shuttleGray,
    blackRock: colors.blackRock,
    torchRed: colors.torchRed,
    blackCoral: colors.blackCoral,
    greenishBlue: colors.greenishBlue,
    mineShaft: colors.mineShaft,

    // NEW DESIGN COLORS
    dark: colors.dark,
    backgroundDarkBlue: colors.backgroundDarkBlue,
    grey: colors.grey,
    blue: colors.secondary,
    borderGrey: colors.borderGrey,
    newBackgroundGray: colors.newBackgroundGray,
    crimsonRed: colors.crimsonRed,
    lightBorderGrey: colors.lightBorderGrey,
    secondaryLight: colors.secondaryLight,
    grayOpacity50: colors.grayOpacity50,
  },
}
